baseurl = "https://blog.wildanfauzy.com"
copyright = "2012 - 2021 ©"
disqusshortname = "wildanfauzy"
languagecode = "id-ID"
paginate = 8
title = "Blog"

[[menu.main]]
weight = 107
name = "Perpus"
url = "https:///perpus.wildanfauzy.com"
[[menu.main]]
weight = 108
name = "Jurnal"
url = "https:///jurnal.wildanfauzy.com"
[[menu.main]]
weight = 114
name = "Newsletter"
url = "https:///surat.wildanfauzy.com"
[[menu.main]]
weight = 105
name = "Cari"
url = "https://blog.wildanfauzy.com/search"
[[menu.main]]
weight = 106
name = "Sign In"
url = "https://blog.wildanfauzy.com/admin/#/login"

[params]
author = "wilfauzy"
authorlocation = "Bandung, Indonesia"
authorwebsite = "https://wildanfauzy.com"
authorbio = "Artikel pilihan dari dapur redaksi"
cover = "/images/header.webp"
description = "WildanFauzy.com adalah blog yang membahas info menarik disajikan secara asik dan santai, kumpulan cerita dari sudut pandang yang berbeda"
githubName = "wilfauzy"
pinterestName = "wilfauzy"
RSSLink = "https://news.google.com/publications/CAAqBwgKMKm2lQswupqrAw" 
hideHUGOSupport = false
disableHugoGeneratorInject = true 
logo = "/img/about.png"
twitterName = "wilfauzy"
#pinterestName = "wilfauzy"
hjsStyle = "default"
[permalinks]
post = "/:slug/"

[params.social]
twitter = "wilfauzy"
github = "wilfauzy"
pinteres = "wilfauzy"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
