baseurl = "https://wilfauzy.com"
copyright = " ©"
disqusshortname = ""
languagecode = "id-ID"
paginate = 8
summaryLength = 25
title = "wilfauzy blog"
[[menu.main]]
name = "Masuk"
url = "https://wilfauzy.com/admin"
weight = 3
[[menu.main]]
name = "Jurnal"
url = "https:///jurnal.wildanfauzy.com"
weight = 5
[[menu.main]]
name = "Notes"
url = "https:///notes.wildanfauzy.com"
weight = 4
[[menu.main]]
name = "Status"
url = "https:///status.wildanfauzy.com"
weight = 6
[[menu.main]]
name = "Perpus"
url = "https:///perpus.wildanfauzy.com"
weight = 7
[[menu.main]]
name = "Surat"
url = "https:///surat.wildanfauzy.com"
weight = 8
[[menu.main]]
name = "Cari"
url = "https:///wilfauzy.com/cari"
weight = 1
[params]
RSSLink = "https://news.google.com/publications/CAAqBwgKMKm2lQswupqrAw"
author = "wilfauzy"
authorbio = "Artikel pilihan dari dapur redaksi"
authorlocation = "Bandung, Indonesia"
authorwebsite = ""
cover = "/images/header.webp"
description = "wilfauzy blog adalah media yang membahas info menarik disajikan secara asik dan santai, kumpulan cerita dari sudut pandang yang berbeda"
disableHugoGeneratorInject = true
githubName = "wilfauzy"
hideHUGOSupport = false
hjsStyle = "default"
logo = "/gambar/logo.png"
pinterestName = "wilfauzy"
twitterName = "wilfauzy"
[params.social]
github = "wilfauzy"
pinteres = "wilfauzy"
twitter = "wilfauzy"
[permalinks]
post = "/:slug/"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
[params.search_config]
app_id = "VKCMJOJYDJ"
api_key = "e7afa02fda735899091f8bc6aa6da167"
index = "blog"
