baseurl = "https://wildanfauzy.com"
copyright = "Hak Cipta Sebagian"
disqusshortname = "wildanfauzy"
languagecode = "id-ID"
paginate = 8
title = "Kandang Babi"

[[menu.main]]
weight = 109
name = "Perpus"
url = "https:///perpus.wildanfauzy.com"
[[menu.main]]
weight = 108
name = "Cari"
url = "https://search.wildanfauzy.com"

[params]
author = "wilfauzy"
authorlocation = "Bandung, Indonesia"
authorwebsite = "https://wildanfauzy.com"
authorbio = "Artikel pilihan dari dapur redaksi"
cover = "/images/header.jpg"
description = "Kandang babi hanya julukan sebuah tempat tinggal, Benda mati dan juga tidak bernapas, tetapi mempunyai nama, perkenalkan namanya adalah “Kandang Babi”"
githubName = "wilfauzy"
pinterestName = "wilfauzy"
RSSLink = "https://news.google.com/publications/CAAqBwgKMKm2lQswupqrAw" 
hideHUGOSupport = false
disableHugoGeneratorInject = true 
logo = "/img/about.png"
twitterName = "wilfauzy"
#pinterestName = "wilfauzy"
hjsStyle = "default"
[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"

[params.social]
twitter = "wilfauzy"
github = "wilfauzy"
pinteres = "wilfauzy"
