baseurl = "https://wildanfauzy.com"
copyright = "Hak Cipta Sebagian"
disqusshortname = "wildanfauzy"
languagecode = "id-ID"
paginate = 8
title = "Kandang Babi"
[[menu.main]]
name = "Cari Sesuatu?"
url = "https://search.wildanfauzy.com"
weight = 100
[[menu.main]]
identifier = "Masuk"
name = "Log in"
url = "https://app.wildanfauzy.com/"
weight = -120
[[menu.main]]
identifier = "Surat"
name = "Surat"
url = "https://surat.wildanfauzy.com"
weight = -119
[[menu.main]]
identifier = "Perpus"
name = "Perpus"
url = "https:///perpus.wildanfauzy.com"
weight = -118
[[menu.main]]
name = "Kompas"
url = "https://kompasiana.com/wildanfauzy"
weight = 101
[[menu.main]]
name = "Medium"
url = "https://jurnal.wildanfauzy.com"
weight = 102
[[menu.main]]
name = "Kaskus"
url = "https://kaskus.co.id/@nadliw45"
weight = 109

[params]
author = "wilfauzy"
authorlocation = "Bandung, Indonesia"
authorwebsite = "https://wildanfauzy.com"
authorbio = "Artikel pilihan dari dapur redaksi"
cover = "/img/jordan-scott-1WflL6VWNh0-unsplash.jpg"
description = "Kandang babi hanya julukan sebuah tempat tinggal, Benda mati dan juga tidak bernapas, tetapi mempunyai nama, perkenalkan namanya adalah “Kandang Babi”"
githubName = "wilfauzy"
pinterestName = "wilfauzy"
RSSLink = "https://news.google.com/publications/CAAqBwgKMKm2lQswupqrAw" 
hideHUGOSupport = false
disableHugoGeneratorInject = true 
logo = "/img/about.png"
twitterName = "wilfauzy"
#pinterestName = "wilfauzy"
hjsStyle = "default"
[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"

[params.social]
twitter = "wilfauzy"
github = "wilfauzy"
pinteres = "wilfauzy"
