baseurl = "https://wildanfauzy.com"
copyright = "some rights reserved"
canonifyurls = true
disqusshortname = "wildanfauzy"
languagecode = "id-ID"
paginate = 5
pluralizelisttitles = false
title = "WildanFauzy.com"
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -120
[[menu.main]]
name = "Search"
pre = "<h3>Follow me</h3>"
url = "https://search.wildanfauzy.com"
weight = 100
[[menu.main]]
identifier = "Login"
name = "Login"
url = "https://app.wildanfauzy.com"
weight = -120
[[menu.main]]
name = "Twitter"
url = "https://twitter.com/wilfauzy"
weight = 101
[[menu.main]]
name = "Medium"
url = "https://medium.com/@wilfauzy"
weight = 102
[[menu.main]]
name = "Instagram"
pre = "<h3>Contact me</h3>"
url = "https://instagram.com/wilfauzy"
weight = 109

[params]
author = "Redaksi"
authorlocation = ""
authorwebsite = ""
authorbio = ""
cover = "/img/unsplash-image-2.jpg"
description = "WildanFauzy.com adalah blog yang membahas info menarik disajikan secara asik dan santai, kumpulan cerita dari sudut pandang yang berbeda"
githubName = "wilfauzy"
googleAnalyticsUserID = ""
hideHUGOSupport = true
logo = "/img/about.png"
twitterName = "WilFauzy"
hjsStyle = "agate"

[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"

[params.social]
twitter = "wilfauzy"
github = "wilfauzy"

