aliases = ["/post/", "/categories/", "/tags/", "/"]
baseurl = "https://blog.wildanfauzy.com"
copyright = "2012 - 2021 ©"
disqusshortname = "wildanfauzy"
languagecode = "id-ID"
paginate = 8
title = "Wildan Fauzy Blog"
[[menu.main]]
name = "Status"
url = "https://status.wildanfauzy.com/"
weight = 2
[[menu.main]]
name = "Cari"
url = "https://blog.wildanfauzy.com/search"
weight = 1
[[menu.main]]
name = "Sign In"
url = "https://blog.wildanfauzy.com/admin/#/login"
weight = 3
[[menu.main]]
name = "Jurnal"
url = "https:///jurnal.wildanfauzy.com"
weight = 5
[[menu.main]]
name = "Perpus"
url = "https:///perpus.wildanfauzy.com"
weight = 4
[[menu.main]]
name = "Newsletter"
url = "https:///surat.wildanfauzy.com"
weight = 11
[[menu.main]]
name = "Kompasiana"
url = "https://www.kompasiana.com/wildanfauzy"
weight = 12
[[menu.main]]
name = "Kaskus"
url = "https://www.kaskus.co.id/@nadliw45"
weight = 8
[params]
RSSLink = "https://news.google.com/publications/CAAqBwgKMKm2lQswupqrAw"
author = "wilfauzy"
authorbio = "Artikel pilihan dari dapur redaksi"
authorlocation = "Bandung, Indonesia"
authorwebsite = "https://wildanfauzy.com"
cover = "/images/header.webp"
description = "Wildan Fauzy Blog adalah media yang membahas info menarik disajikan secara asik dan santai, kumpulan cerita dari sudut pandang yang berbeda"
disableHugoGeneratorInject = true
githubName = "wilfauzy"
hideHUGOSupport = false
hjsStyle = "default"
logo = "/images/logo.png"
pinterestName = "wilfauzy"
twitterName = "wilfauzy"
[params.social]
github = "wilfauzy"
pinteres = "wilfauzy"
twitter = "wilfauzy"
[permalinks]
post = "/:slug/"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
