baseurl = "https://wildanfauzy.com"
copyright = "Some rights reserved"
disqusshortname = "wildanfauzy"
languagecode = "id-ID"
paginate = 8
pluralizelisttitles = false
canonifyurls = false
title = "Wildan Fauzy Stories"
[[menu.main]]
name = "Search"
url = "https://search.wildanfauzy.com"
weight = 100
[[menu.main]]
identifier = "Submit"
name = "Submit"
url = "https://app.wildanfauzy.com/#/"
weight = -120
[[menu.main]]
identifier = "Surat"
name = "Surat"
url = "https://surat.wildanfauzy.com"
weight = -119
[[menu.main]]
identifier = "Perpus"
name = "Perpus"
url = "https:///perpus.wildanfauzy.com"
weight = -118
[[menu.main]]
name = "Kompas"
url = "https://kompasiana.com/wildanfauzy"
weight = 101
[[menu.main]]
name = "Jurnal"
url = "https://jurnal.wildanfauzy.com"
weight = 102
[[menu.main]]
name = "Galeri"
url = "https://pinterest.com/wilfauzy"
weight = 109

[params]
author = "Wildan Fauzy"
authorlocation = "Bandung, Indonesia"
authorwebsite = "https://idan.my.id"
authorbio = "Artikel pilihan dari dapur redaksi"
cover = "/img/black-landscape-2.jpg"
description = "WildanFauzy.com adalah blog yang membahas info menarik disajikan secara asik dan santai, kumpulan cerita dari sudut pandang yang berbeda"
githubName = "wilfauzy"
googleAnalyticsUserID = "UA-168081661-1"
RSSLink = "https://news.google.com/publications/CAAqBwgKMKm2lQswupqrAw" 
hideHUGOSupport = false
disableHugoGeneratorInject = true
logo = "/img/about.png"
twitterName = "WilFauzy"
mediumName ="wilfauzy" 
#facebookName = ""
instagramName = "wilfauzy"
hjsStyle = "agate"
[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"

[params.social]
twitter = "wilfauzy"
github = "wilfauzy"
medium = "wilfauzy" 