[build]
  publish = "public"
  command = "hugo --minify"
  
[build.environment]
  HUGO_VERSION = "0.88.1"
  
[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

  [plugins.inputs]
  debug = true
  srcdir = "./"
