[build]
  publish = "public"
  command = "hugo --gc --minify"
  base = ".rahasia"

[build.environment]
  HUGO_VERSION = "0.89.4"
  HUGO_BASEURL = "https://blog.wildanfauzy.com"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "document-domain=()"
    Content-Security-Policy = "frame-ancestors 'none';"
