name = "www"
type = "javascript"
account_id = "79acc6c68003ac9ef4666a7a5ccf8761"
workers_dev = true

[env.production]
workers_dev = false
route = "wildanfauzy.com/*"
zone_id = "52d8fe4a315f4d8d9f91883d381dc44f"

[site]
bucket = "./public"
entry-point = "workers-site"