name: hugo-remote

on:
  push:
    branches:
      - master

env:
  REMOTE: wilfauzy/wilfauzy.github.io.git
  DEST: public
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
      - name: 🚀 Build and deploy
        uses: victoriadrake/hugo-remote@master
        with:
          branch: master
          commit_message: kok gitu sih